### ISSUE TITLE
Latest Docker Fail to compile API and BOT for Productions

### ISSUE THREAD

**Issue by ranrinc** [ZeppelinBot/Zeppelin#405]
Fresh Install without any applications using the Production environment:
Server Host on AWS Lightsail
OS: Debian Bullseye 11.4
Docker ver: 23.0.5, build bc4487a
Docker Compose ver: v2.9.0

Running for the first time:
`docker compose -f docker-compose.production.yml up -d` without any error and all docker containers run as expected. However `zeppelin-prod-prepare_backend-1` will instantly crash/fail causing a domino effect toward the rest of the container which is actually trying to run with an error

Error Logs
API logs:
```
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the API...

Starting API
> @zeppelin/backend@0.0.1 start-api-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/api/index.js
sh: 1: cross-env: not found
```

BOT logs:
```
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
sh: 1: cross-env: not found
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
Waiting for prepare_backend to finish before starting the bot...

Starting bot
> @zeppelin/backend@0.0.1 start-bot-prod
> cross-env NODE_ENV=production node -r ./register-tsconfig-paths.js --unhandled-rejections=strict --enable-source-maps --stack-trace-limit=30 dist/backend/src/index.js
sh: 1: cross-env: not found
```
Dashboard Logs:
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
added 1133 packages, and audited 1134 packages in 58s
66 packages are looking for funding
  run `npm fund` for details
37 vulnerabilities (1 low, 6 moderate, 26 high, 4 critical)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.6
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.6>
npm notice Run `npm install -g npm@9.6.6` to update!
npm notice 
> @zeppelin/dashboard@1.0.0 build
> rimraf dist && cross-env NODE_ENV=production webpack --config webpack.config.js
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/zeppelin/dashboard/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:471:10)
    at /zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:503:5
    at /zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:358:12
    at /zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/zeppelin/dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /zeppelin/dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /zeppelin/dashboard/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/zeppelin/dashboard/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:471:10)
    at /zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:503:5
    at /zeppelin/dashboard/node_modules/webpack/lib/NormalModule.js:358:12
    at /zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/zeppelin/dashboard/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /zeppelin/dashboard/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v18.16.0
```

Backend Logs:
```
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.6
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.6>
npm notice Run `npm install -g npm@9.6.6` to update!
npm notice 
npm ERR! code EUSAGE

 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

 
npm ERR! Missing: typescript@5.0.4 from lock file

 
npm ERR! Clean install a project

 
npm ERR! Usage:
npm ERR! npm ci

 
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global]
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]

 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean

 
npm ERR! Run "npm help ci" for more info
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-05-07T05_12_41_806Z-debug-0.log
```
I hope this will get fixed and I believe need to test for a fresh install not for an update since the update might not require rebuilding the Backend or Dashboard.

**Comment by Dragory** [comment]
Can you try with commit https://github.com/ZeppelinBot/Zeppelin/commit/025e67d6b65c893de58740443c8f31176eca0da8? That's the latest stable version; the commits after are part of the May update that's yet to be released.

I'll make sure this is resolved before the full update is out however.
